import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CustomLinks from "./components/CustomLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <ul className="flex gap-5 mb-6">
            <li><CustomLinks path="/">home</CustomLinks></li>
            <li><CustomLinks path="/dashboard/setting">setting</CustomLinks></li>
            <li><CustomLinks path="/dashboard/analysis">analysis</CustomLinks></li>
          </ul>
        </div>
        {children}
        </body>
    </html>
  );
}
